# flake8: noqa
# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-18 09:03
from __future__ import unicode_literals

from django.db import migrations, models
import oauth2client.contrib.django_util.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('email', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('credential', oauth2client.contrib.django_util.models.CredentialsField(null=True)),
            ],
        ),
    ]
