# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-08 09:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dropbucket',
            options={'ordering': ['name']},
        ),
    ]
