language: python

# python 2.7.6 archive is only available on trusty
dist: trusty

python:
  - "2.7.6"
  - "2.7"
  - "3.6"
before_install:
  # https://github.com/travis-ci/travis-ci/issues/7940#issuecomment-310759657
  - sudo rm -f /etc/boto.cfg
  - pip install --upgrade setuptools pip wheel
script:
  - make
notifications:
  slack: ccnmtl:GizSNscLWJLldjQrffB8mwgm
