language: python
dist: xenial
python:
  - "2.7"
  - "3.4"
  - "3.6"
before_install:
  # https://github.com/travis-ci/travis-ci/issues/7940#issuecomment-310759657
  - sudo rm -f /etc/boto.cfg
  - pip install --upgrade setuptools pip wheel
script:
  - make
notifications:
  slack: ccnmtl:GizSNscLWJLldjQrffB8mwgm
