# flake8: noqa
# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-08 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StreamLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.TextField(blank=True)),
                ('remote_addr', models.TextField(blank=True)),
                ('offset', models.TextField(blank=True)),
                ('referer', models.TextField(blank=True)),
                ('user_agent', models.TextField(blank=True)),
                ('access', models.TextField(blank=True)),
                ('request_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
