# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-08 10:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamlogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='streamlog',
            options={'ordering': ['-request_at']},
        ),
    ]
