# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20161209_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='uuid',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='operation',
            name='uuid',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='video',
            name='uuid',
            field=models.UUIDField(),
        ),
    ]
