# flake8: noqa
# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-25 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20170630_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='location_type',
            field=models.CharField(choices=[(b'pcp', b'pcp'), (b'cuit', b'cuit'), (b'youtube', b'youtube'), (b's3', b's3'), (b'panopto', b'panopto'), (b'none', b'none')], default=b's3', max_length=256),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.CharField(max_length=1024),
        ),
    ]
