# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-08 11:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20180525_2205'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('name', models.CharField(blank=True, max_length=1024, null=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Video')),
            ],
        ),
    ]
