# flake8: noqa
# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-12 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import wardenclyffe.main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_videoreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='collection',
            field=models.ForeignKey(on_delete=models.SET(wardenclyffe.main.models.unclassified), to='main.Collection'),
        ),
    ]
