# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-13 10:16
from __future__ import unicode_literals

from django.db import migrations


def remove_orphan_mediathread_asset(apps, schema_editor):
    File = apps.get_model('main', 'File')
    ids = []
    for f in File.objects.filter(location_type='mediathread'):
        video = f.video
        qs = video.file_set.filter(location_type__in=['cuit', 'panopto'])
        if qs.count() < 1:
            ids.append(f.id)

    File.objects.filter(id__in=ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20180612_1515'),
    ]

    operations = [
        migrations.RunPython(remove_orphan_mediathread_asset),
    ]
