# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-15 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20180613_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='st_size',
            field=models.IntegerField(default=0),
        ),
    ]
