name: build-and-test
on: [push]
jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
          python-version: ["3.8", "3.12"]
    services:
      rabbitmq:
        image: rabbitmq:3.8
        ports:
          - 5672:5672
    steps:
      - uses: actions/checkout@v4
      - name: Run eslint
        run: make eslint
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Build with Makefile
        run: make
